@extends('main.component.js.index')
@extends('main.component.master.footer')
@extends('main.component.chat.chatContent')	
@extends('main.page.news.newsHeader')	
@extends('main.component.master.sidebar')
@extends('main.component.master.index')